"""Simulated SAS Intelligent Decisioning.

Production swap: rule sets and decision flows are authored in SAS Intelligent
Decisioning, published to MAS, and executed through the sas-mcp-server tools
(list_models_and_decisions / score_data and the Tier-7 decisioning tools).
This module reproduces the observable behavior: versioned rule sets, no-code
edits, publish, execute-with-rule-fire-trace, and generated DS2 preview.
"""

import copy
from datetime import datetime, timezone

from store import store


def get_state():
    rs = store.ruleset
    published = rs["versions"][rs["publishedVersion"]]
    return {
        "ruleSetId": rs["ruleSetId"], "name": rs["name"],
        "flowId": rs["flowId"], "flowName": rs["flowName"],
        "masModule": rs["masModule"],
        "publishedVersion": rs["publishedVersion"],
        "draftVersion": rs["draftVersion"],
        "rules": published["rules"],
        "draftRules": rs["versions"].get(rs["draftVersion"], {}).get("rules") if rs["draftVersion"] else None,
        "history": rs["history"],
        "ds2Preview": generate_ds2(published["rules"]),
    }


def generate_ds2(rules) -> str:
    threshold = _threshold_of(rules)
    return f"""/* Generated by SAS Intelligent Decisioning (simulated preview) */
package inflation_allowance_eligibility / overwrite=yes;
  method execute(double monthlyIncomeAED, varchar(3) nationality,
                 double familySize, double verifiedWithinMonths,
                 in_out varchar(16) outcome, in_out double confidence);
    outcome = 'INELIGIBLE';
    if nationality = 'UAE'
       and familySize >= 1
       and monthlyIncomeAED <= {threshold}
       and verifiedWithinMonths <= 12 then do;
      outcome = 'ELIGIBLE';
    end;
    confidence = 0.93;
  end;
endpackage;"""


def _threshold_of(rules) -> float:
    for r in rules:
        if r["ruleId"] == "INC-004":
            return r["params"]["threshold"]
    return 25000


def update_rule(rule_id: str, params: dict, actor: str):
    """No-code edit -> creates/updates a draft version (never mutates published)."""
    rs = store.ruleset
    if rs["draftVersion"] is None:
        new_v = rs["publishedVersion"] + 1
        rs["versions"][new_v] = {
            "version": new_v, "publishedAt": None, "publishedBy": None,
            "note": "Draft", "rules": copy.deepcopy(rs["versions"][rs["publishedVersion"]]["rules"]),
        }
        rs["draftVersion"] = new_v
    draft = rs["versions"][rs["draftVersion"]]
    for r in draft["rules"]:
        if r["ruleId"] == rule_id:
            if not r.get("editable"):
                raise ValueError(f"Rule {rule_id} is locked")
            r["params"].update(params)
            r["lastEditedBy"] = actor
            return get_state()
    raise ValueError(f"Rule {rule_id} not found")


def publish(note: str, actor: str):
    rs = store.ruleset
    if rs["draftVersion"] is None:
        raise ValueError("No draft to publish")
    v = rs["draftVersion"]
    rs["versions"][v]["publishedAt"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rs["versions"][v]["publishedBy"] = actor
    rs["versions"][v]["note"] = note
    rs["publishedVersion"] = v
    rs["draftVersion"] = None
    rs["history"].append({"version": v, "publishedAt": rs["versions"][v]["publishedAt"], "note": note})
    return get_state()


def execute_flow(payload: dict, version: int | None = None):
    """Execute the decision flow; returns outcome + per-rule fire trace.

    payload: {monthlyIncomeAED, nationality, familySize, verifiedWithinMonths}
    """
    rs = store.ruleset
    v = version or rs["publishedVersion"]
    rules = rs["versions"][v]["rules"]
    threshold = _threshold_of(rules)
    fires = []

    def fire(rule_id, name, passed, detail):
        fires.append({"ruleId": rule_id, "name": name, "passed": passed, "detail": detail})
        return passed

    ok = True
    ok &= fire("INC-001", "Nationality gate", payload.get("nationality") == "UAE",
               f"nationality = {payload.get('nationality')}")
    ok &= fire("INC-002", "Head of household", payload.get("familySize", 0) >= 1,
               f"familySize = {payload.get('familySize')}")
    income = payload.get("monthlyIncomeAED", 0)
    ok &= fire("INC-004", "Income threshold", income <= threshold,
               f"income AED {income:,.0f} vs threshold AED {threshold:,.0f}")
    vm = payload.get("verifiedWithinMonths", 99)
    ok &= fire("INC-007", "Verification recency", vm <= 12,
               f"verified {vm} month(s) ago")
    outcome = "ELIGIBLE" if ok else "INELIGIBLE"
    fires.append({"ruleId": "OUT-001", "name": "Outcome mapping", "passed": True,
                  "detail": f"outcome = {outcome}"})
    return {
        "flow": rs["flowName"], "masModule": rs["masModule"], "version": v,
        "outcome": outcome, "confidence": 0.93 if ok else 0.91,
        "ruleFires": fires, "threshold": threshold,
    }
