"""SAS Intelligent Decisioning — live via MCP, simulated as fallback.

Rule sets and decision flows are authored in SAS Intelligent Decisioning and
published to MAS. When SAS_MCP_URL is set, execute_flow scores the payload on
the REAL published module through the sas-mcp-server's `score_data` tool
(see sas_id.py and docs/SAS_ID_SETUP.md); the in-process rules below then only
render the per-rule fire trace. Without SAS_MCP_URL, the same rules decide the
outcome (versioned rule sets, no-code edits, publish, DS2 preview).
Every result carries `executedOn` so the UI can badge honestly.
"""

import copy
from datetime import datetime, timezone

import sas_id
from store import store


def get_state():
    rs = store.ruleset
    published = rs["versions"][rs["publishedVersion"]]
    return {
        "ruleSetId": rs["ruleSetId"], "name": rs["name"],
        "flowId": rs["flowId"], "flowName": rs["flowName"],
        "masModule": rs["masModule"],
        "publishedVersion": rs["publishedVersion"],
        "draftVersion": rs["draftVersion"],
        "rules": published["rules"],
        "draftRules": rs["versions"].get(rs["draftVersion"], {}).get("rules") if rs["draftVersion"] else None,
        "history": rs["history"],
        "ds2Preview": generate_ds2(published["rules"]),
    }


def generate_ds2(rules) -> str:
    threshold = _threshold_of(rules)
    return f"""/* Generated by SAS Intelligent Decisioning (simulated preview) */
package inflation_allowance_eligibility / overwrite=yes;
  method execute(double monthlyIncomeAED, varchar(3) nationality,
                 double familySize, double verifiedWithinMonths,
                 in_out varchar(16) outcome, in_out double confidence);
    outcome = 'INELIGIBLE';
    if nationality = 'UAE'
       and familySize >= 1
       and monthlyIncomeAED <= {threshold}
       and verifiedWithinMonths <= 12 then do;
      outcome = 'ELIGIBLE';
    end;
    confidence = 0.93;
  end;
endpackage;"""


def _threshold_of(rules) -> float:
    for r in rules:
        if r["ruleId"] == "INC-004":
            return r["params"]["threshold"]
    return 25000


def update_rule(rule_id: str, params: dict, actor: str):
    """No-code edit -> creates/updates a draft version (never mutates published)."""
    rs = store.ruleset
    if rs["draftVersion"] is None:
        new_v = rs["publishedVersion"] + 1
        rs["versions"][new_v] = {
            "version": new_v, "publishedAt": None, "publishedBy": None,
            "note": "Draft", "rules": copy.deepcopy(rs["versions"][rs["publishedVersion"]]["rules"]),
        }
        rs["draftVersion"] = new_v
    draft = rs["versions"][rs["draftVersion"]]
    for r in draft["rules"]:
        if r["ruleId"] == rule_id:
            if not r.get("editable"):
                raise ValueError(f"Rule {rule_id} is locked")
            r["params"].update(params)
            r["lastEditedBy"] = actor
            return get_state()
    raise ValueError(f"Rule {rule_id} not found")


def publish(note: str, actor: str):
    rs = store.ruleset
    if rs["draftVersion"] is None:
        raise ValueError("No draft to publish")
    v = rs["draftVersion"]
    rs["versions"][v]["publishedAt"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    rs["versions"][v]["publishedBy"] = actor
    rs["versions"][v]["note"] = note
    rs["publishedVersion"] = v
    rs["draftVersion"] = None
    rs["history"].append({"version": v, "publishedAt": rs["versions"][v]["publishedAt"], "note": note})
    return get_state()


def execute_flow(payload: dict, version: int | None = None):
    """Execute the decision flow; returns outcome + per-rule fire trace.

    payload: {monthlyIncomeAED, nationality, familySize, verifiedWithinMonths}
    """
    rs = store.ruleset
    v = version or rs["publishedVersion"]
    rules = rs["versions"][v]["rules"]
    threshold = _threshold_of(rules)
    fires = []

    def fire(rule_id, name, passed, detail):
        fires.append({"ruleId": rule_id, "name": name, "passed": passed, "detail": detail})
        return passed

    ok = True
    ok &= fire("INC-001", "Nationality gate", payload.get("nationality") == "UAE",
               f"nationality = {payload.get('nationality')}")
    ok &= fire("INC-002", "Head of household", payload.get("familySize", 0) >= 1,
               f"familySize = {payload.get('familySize')}")
    income = payload.get("monthlyIncomeAED", 0)
    ok &= fire("INC-004", "Income threshold", income <= threshold,
               f"income AED {income:,.0f} vs threshold AED {threshold:,.0f}")
    vm = payload.get("verifiedWithinMonths", 99)
    ok &= fire("INC-007", "Verification recency", vm <= 12,
               f"verified {vm} month(s) ago")
    outcome = "ELIGIBLE" if ok else "INELIGIBLE"
    confidence = 0.93 if ok else 0.91
    executed_on = "Simulated rule engine (in-process)"
    mas_outputs = None

    if sas_id.enabled():
        live = sas_id.execute(payload)
        if live["ok"]:
            outcome = live["outcome"] or outcome
            confidence = live["confidence"] if live["confidence"] is not None else confidence
            executed_on = live["executedOn"]
            mas_outputs = live["outputs"]
        else:
            executed_on = f"Simulated rule engine (SAS ID fallback — {live['error']})"

    fires.append({"ruleId": "OUT-001", "name": "Outcome mapping", "passed": True,
                  "detail": f"outcome = {outcome}"})
    return {
        "flow": rs["flowName"], "masModule": rs["masModule"], "version": v,
        "outcome": outcome, "confidence": confidence,
        "ruleFires": fires, "threshold": threshold,
        "executedOn": executed_on, "masOutputs": mas_outputs,
        "live": mas_outputs is not None,
    }
